package jjcet.PragatiX.enums;

public enum AuditAction {
    CREATE,
    UPDATE,
    DELETE,
    RESTORE,
    PERMANENT_DELETE,
    LOGIN,
    LOGOUT,
    EXPORT,
    ASSIGN,
    UNASSIGN,
    APPROVE,
    REJECT,
    AWARD_XP,
    PENALTY_XP,
    ADD_MEMBER,
    REMOVE_MEMBER,
    CHANGE_CAPTAIN,
    CHANGE_VICE_CAPTAIN,
    ENROLLMENT_IMPORT,
    ENROLLMENT_CREATED,
    ENROLLMENT_COMPLETED,
    ENROLLMENT_SETTING_CHANGED,
    OTHER
}
